sudo: required
services:
  - docker
before_install:
  - docker build -t corewar .
script:
  - docker run corewar npm run test

after_success:
  - npm run coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag corewar dougajmcdonald/corewar:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dougajmcdonald/corewar;
    fi
