sudo: required
services:
  - docker

before_install:

script:
  - npm install
  - npm run test
  - npm run coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t corewar .
    docker tag corewar $DOCKER_USERNAME/corewar:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/corewar;
    fi
