sudo: required
services:
  - docker

before_install:
  - docker build -t corewar .
script:
  - npm run coveralls
  - docker run corewar npm run test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag corewar $DOCKER_USERNAME/corewar:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/corewar;
    fi
