sudo: required
services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t corewar .

    - stage: test in container
      script:
      - docker run corewar npm run test

    script:
      - npm run coveralls

    after_success:
      - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker tag corewar $DOCKER_USERNAME/corewar:latest;
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push dougajmcdonald/corewar;
        fi
