sudo: required
services:
  - docker
before_install:
  - docker build -t corewar .
script:
  - docker run corewar npm run test && npm run lint

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag corewar dougajmcdonald/corewar:$(git rev-parse --short HEAD);
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dougajmcdonald/corewar;
    fi
